force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Plane__c.field-meta.xml
<CustomField>
    <fullName>Plane__c</fullName>
    <label>Plane</label>
    <referenceTo>Plane__c</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plane__c/Plane__c.object-meta.xml
<CustomObject>
    <label>Plane</label>
    <nameField>
        <label>Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plane__c/fields/Plane_Type__c.field-meta.xml
<CustomField>
    <fullName>Plane_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plane Type</label>
    <referenceTo>Plane_Type__c</referenceTo>
    <relationshipLabel>Planes</relationshipLabel>
    <relationshipName>Planes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/Plane_Type__c.object-meta.xml
<CustomObject>
    <label>Plane Type</label>
    <nameField>
        <label>Plane Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plane Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plane_Type__c/fields/Business_seats__c.field-meta.xml
<CustomField>
    <fullName>Business_seats__c</fullName>
    <label>Business_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/fields/Economy_seats__c.field-meta.xml
<CustomField>
    <fullName>Economy_seats__c</fullName>
    <label>Economy_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/fields/First_seats__c.field-meta.xml
<CustomField>
    <fullName>First_seats__c</fullName>
    <label>First_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/triggers/helpers/FlightTriggerHelper.cls
/**
 * Created by igorkarpiuk on 07.06.2021.
 */

public with sharing class FlightTriggerHelper {

    private static final Integer firstIndex = 0;
    private static final Integer businessIndex = 1;
    private static final Integer economyIndex = 2;

    public static void createTickets(List<Flight__c> flights) {

        List<Ticket__c> tickets = new List<Ticket__c>();
        List<Schema.PicklistEntry> ticketTypes = Ticket__c.Class__c.getDescribe().getPicklistValues();

        for (Flight__c flight : flights) {


            Plane_Type__c type = [
                    SELECT Id, Name, Business_seats__c, First_seats__c, Economy_seats__c
                    FROM Plane_Type__c
                    WHERE Id IN (SELECT Plane_Type__c FROM Plane__c WHERE Id = :flight.Plane__c)
            ];


            for (Integer i = 0; i < type.First_seats__c; i++) {
                tickets.add(
                        new Ticket__c(Name = flight.Name, Flight__c = flight.Id,
                                Class__c = ticketTypes[firstIndex].getLabel())
                );
            }

            for (Integer i = 0; i < type.Business_seats__c; i++) {
                tickets.add(new Ticket__c(Name = flight.Name, Flight__c = flight.Id,
                        Class__c = ticketTypes[businessIndex].getLabel()));
            }

            for (Integer i = 0; i < type.Economy_seats__c; i++) {
                tickets.add(new Ticket__c(Name = flight.Name, Flight__c = flight.Id,
                        Class__c = ticketTypes[economyIndex].getLabel()));
            }

        }

        try {
            insert tickets;
        } catch (Exception e) {
            System.debug('ERROR OCCURRED WHILE CREATING TICKETS' + e.getMessage());
        }
    }

}