force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights_from</relationshipLabel>
    <relationshipName>Flights_from</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Plane__c.field-meta.xml
<CustomField>
    <fullName>Plane__c</fullName>
    <label>Plane</label>
    <referenceTo>Plane__c</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights_to</relationshipLabel>
    <relationshipName>Flights_to</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plane__c/Plane__c.object-meta.xml
<CustomObject>
    <label>Plane</label>
    <nameField>
        <label>Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/triggers/tests/FlightTriggerTest.cls
@IsTest
public with sharing class FlightTriggerTest {

//    @TestSetup
//    public static void createData() {
//        MockFactory.createData();
//    }
//
//    @IsTest
//    public static void createTicketsSuccess() {
//        List<Airport__c> airports = [SELECT Id, Name FROM Airport__c LIMIT 2];
//        Plane__c plane = [SELECT Id, Name FROM Plane__c LIMIT 1];
//
//        Flight__c flight = new Flight__c(Name = airports[0].Name + ' - ' + airports[1].Name, Plane__c = plane.Id,
//                From__c = airports[0].Id, To__c = airports[1].Id, Date_and_Time__c = Datetime.now());
//
//        insert flight;
//
//        List<Ticket__c> tickets = [SELECT Id, Name FROM Ticket__c];
//
//        System.assertEquals(3, tickets.size());
//    }
}