force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Business_tickets__c.field-meta.xml
<CustomField>
    <fullName>Business_tickets__c</fullName>
    <label>Business_tickets</label>
    <summaryFilterItems>
        <field>Ticket__c.Class__c</field>
        <operation>equals</operation>
        <value>Business</value>
    </summaryFilterItems>
    <summaryForeignKey>Ticket__c.Flight__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure_date__c.field-meta.xml
<CustomField>
    <fullName>Departure_date__c</fullName>
    <label>Departure date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Economy_tickets__c.field-meta.xml
<CustomField>
    <fullName>Economy_tickets__c</fullName>
    <label>Economy_tickets</label>
    <summaryFilterItems>
        <field>Ticket__c.Class__c</field>
        <operation>equals</operation>
        <value>Economy</value>
    </summaryFilterItems>
    <summaryForeignKey>Ticket__c.Flight__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/First_tickets__c.field-meta.xml
<CustomField>
    <fullName>First_tickets__c</fullName>
    <label>First_tckets</label>
    <summaryFilterItems>
        <field>Ticket__c.Class__c</field>
        <operation>equals</operation>
        <value>First</value>
    </summaryFilterItems>
    <summaryForeignKey>Ticket__c.Flight__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights_from</relationshipLabel>
    <relationshipName>Flights_from</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Plane__c.field-meta.xml
<CustomField>
    <fullName>Plane__c</fullName>
    <label>Plane</label>
    <referenceTo>Plane__c</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights_to</relationshipLabel>
    <relationshipName>Flights_to</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plane__c/Plane__c.object-meta.xml
<CustomObject>
    <label>Plane</label>
    <nameField>
        <label>Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plane__c/fields/Plane_Type__c.field-meta.xml
<CustomField>
    <fullName>Plane_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plane Type</label>
    <referenceTo>Plane_Type__c</referenceTo>
    <relationshipLabel>Planes</relationshipLabel>
    <relationshipName>Planes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/Plane_Type__c.object-meta.xml
<CustomObject>
    <label>Plane Type</label>
    <nameField>
        <label>Plane Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plane Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plane_Type__c/fields/Business_seats__c.field-meta.xml
<CustomField>
    <fullName>Business_seats__c</fullName>
    <label>Business_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/fields/Economy_seats__c.field-meta.xml
<CustomField>
    <fullName>Economy_seats__c</fullName>
    <label>Economy_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/fields/First_seats__c.field-meta.xml
<CustomField>
    <fullName>First_seats__c</fullName>
    <label>First_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First</fullName>
            </value>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FlightService.cls
public with sharing class FlightService {

    @AuraEnabled(Cacheable=true)
    public static List<Plane__c> getPlanes(Id typeId, Date day) {
        List<Plane__c> planes = [
                SELECT Id, Name
                FROM Plane__c
                WHERE Id NOT IN (
                        SELECT Plane__c
                        FROM Flight__c
                        WHERE Departure_date__c = :day
                        AND Plane__r.Plane_Type__c = :typeId
                )
        ];

        return planes;

    }

    @AuraEnabled(Cacheable=true)
    public static List<Airport__c> getAllAirports() {
        return [SELECT Id, Name FROM Airport__c];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Flight__c> getFlights(Id airportFrom, Id airportTo, Date departureDate) {
        List<Flight__c> flights = [
                SELECT Id, Name, Business_tickets__c, Economy_tickets__c, First_tickets__c,
                        Plane__r.Plane_Type__r.Economy_seats__c, Plane__r.Plane_Type__r.Business_seats__c,
                        Plane__r.Plane_Type__r.First_seats__c
                FROM Flight__c
                WHERE From__c = :airportFrom AND To__c = :airportTo AND Departure_date__c = :departureDate
        ];

        return flights;
    }

    @AuraEnabled(Cacheable=false)
    public static void createTicket(String type, Id flight, Id contact) {
        Ticket__c ticket = new Ticket__c(Flight__c = flight, Class__c = type, Passenger__c = contact);
        insert ticket;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Product2> getPrices(Id flightId) {
        List<Product2> products = [
                SELECT Id, (SELECT UnitPrice, Pricebook2.Name FROM PricebookEntries LIMIT 4)
                FROM Product2
                WHERE Id IN (SELECT Product__c FROM Flight__c WHERE Id = :flightId)
        ];

        System.debug(products);
        return products;
    }

}