force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Departure_date__c.field-meta.xml
<CustomField>
    <fullName>Departure_date__c</fullName>
    <label>Departure date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights_from</relationshipLabel>
    <relationshipName>Flights_from</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Plane__c.field-meta.xml
<CustomField>
    <fullName>Plane__c</fullName>
    <label>Plane</label>
    <referenceTo>Plane__c</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights_to</relationshipLabel>
    <relationshipName>Flights_to</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plane__c/Plane__c.object-meta.xml
<CustomObject>
    <label>Plane</label>
    <nameField>
        <label>Plane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plane__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Planes</relationshipLabel>
    <relationshipName>Planes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plane__c/fields/Plane_Type__c.field-meta.xml
<CustomField>
    <fullName>Plane_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plane Type</label>
    <referenceTo>Plane_Type__c</referenceTo>
    <relationshipLabel>Planes</relationshipLabel>
    <relationshipName>Planes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/Plane_Type__c.object-meta.xml
<CustomObject>
    <label>Plane Type</label>
    <nameField>
        <label>Plane Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plane Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plane_Type__c/fields/Business_seats__c.field-meta.xml
<CustomField>
    <fullName>Business_seats__c</fullName>
    <label>Business_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/fields/Economy_seats__c.field-meta.xml
<CustomField>
    <fullName>Economy_seats__c</fullName>
    <label>Economy_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plane_Type__c/fields/First_seats__c.field-meta.xml
<CustomField>
    <fullName>First_seats__c</fullName>
    <label>First_seats</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MockFactory.cls
public with sharing class MockFactory {

 public static void createData() {

  Airport__c[] airports = new Airport__c[] {
            new Airport__c(Name = 'Borispil', Country__c = 'Ukraine', City__c = 'Kyiv'),
            new Airport__c(Name = 'Lviv', Country__c = 'Ukraine', City__c = 'Lviv'),
            new Airport__c(Name = 'Istanbul', Country__c = 'Turkey', City__c = 'Istanbul'),
            new Airport__c(Name = 'Orly', Country__c = 'France', City__c = 'Paris')
    };
     insert airports;

     Account account = new Account(Name = 'MAU');

     insert account;

     Plane_Type__c planeType = new Plane_Type__c(Name = 'Boeing 767', Economy_seats__c = 1,
             Business_seats__c = 1, First_seats__c = 1);

     insert planeType;


     Plane__c plane = new Plane__c(Name = 'Boeing 767 - 1', Plane_Type__c = planeType.Id,
                                   Owner__c = account.Id);
     insert plane;

     Flight__c flight = new Flight__c(Name = 'Lviv - Paris', Plane__c = plane.Id,
             From__c = airports[1].Id, To__c = airports[3].Id, Date_and_Time__c = Datetime.now(), Departure_date__c = Date.today());

  insert flight;


 }
}